platform :ios, '7.0'
use_frameworks!

target 'ProDevForIOS' do
    #pod 'KVNProgress', '~> 2.2.4'
  pod 'YYModel', '~> 0.9.12'
  pod 'YYCache', '~> 1.0'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'Reachability', '~> 3.2'
  pod 'AFNetworking', '~> 3.0'
  pod 'MJRefresh', '~> 3.1.0'
  pod  'SSZipArchive'
  #pod 'MMPopupView', '~> 1.6'
  pod 'Masonry', '~> 0.6.4'
  #(JS_DIR=`pwd`/reactcomponent;cd Pods/React;npm run start -- --root $JS_DIR)
  #react-native bundle --entry-file index.ios.js --bundle-output ./bundle/news.ios.jsbundle --platform ios --assets-dest ./bundle --dev true
end
